import type {
  User,
  HouseUser,
  PersonalUser,
  Post,
  Story,
  Ritual,
  Conversation,
  BoostPlan,
} from "@/types";

const now = Date.now();
const iso = (offsetSec: number) => new Date(now - offsetSec * 1000).toISOString();

export const seedHouses: HouseUser[] = [
  {
    id: "casa_1",
    type: "commercial",
    name: "Ilê Axé Oxum Ferreira",
    email: "oxum@ile.app",
    password: "123456",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop&auto=format",
    cover: "https://images.unsplash.com/photo-1502786129293-79981df4e689?w=1600&h=600&fit=crop",
    bio: "Casa dedicada às águas doces de Mãe Oxum. Rituais de prosperidade, amor e cura.",
    city: "Salvador",
    state: "BA",
    country: "Brasil",
    category: "Candomblé Ketu",
    tags: ["prosperidade", "amor", "cura"],
    rating: 4.9,
    followers: 12800,
    verified: true,
    boost: { level: "pais", expiresAt: iso(-60 * 60 * 24 * 5) },
    createdAt: iso(60 * 60 * 24 * 365),
  },
  {
    id: "casa_2",
    type: "commercial",
    name: "Terreiro de Xangô Airá",
    email: "xango@ile.app",
    password: "123456",
    avatar: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=200&h=200&fit=crop&auto=format",
    cover: "https://images.unsplash.com/photo-1519750157634-b6d493a0f77c?w=1600&h=600&fit=crop",
    bio: "Justiça, força e sabedoria. Trabalhos com o Rei Xangô.",
    city: "Recife",
    state: "PE",
    country: "Brasil",
    category: "Candomblé Nagô",
    tags: ["justiça", "força", "abertura de caminhos"],
    rating: 4.8,
    followers: 8400,
    verified: true,
    boost: { level: "estado", expiresAt: iso(-60 * 60 * 24 * 2) },
    createdAt: iso(60 * 60 * 24 * 500),
  },
  {
    id: "casa_3",
    type: "commercial",
    name: "Ilê Iemanjá das Ondas",
    email: "iemanja@ile.app",
    password: "123456",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&auto=format",
    cover: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1600&h=600&fit=crop",
    bio: "Mãe Iemanjá acolhe seus filhos. Consultas, banhos e obrigações.",
    city: "Rio de Janeiro",
    state: "RJ",
    country: "Brasil",
    category: "Umbanda",
    tags: ["proteção", "família", "maternidade"],
    rating: 4.7,
    followers: 5300,
    verified: false,
    createdAt: iso(60 * 60 * 24 * 200),
  },
  {
    id: "casa_4",
    type: "commercial",
    name: "Casa de Ogum Megê",
    email: "ogum@ile.app",
    password: "123456",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&auto=format",
    cover: "https://images.unsplash.com/photo-1470813740244-df37b8c1edcb?w=1600&h=600&fit=crop",
    bio: "Ogum abre os caminhos! Serviços de desobsessão e proteção.",
    city: "São Paulo",
    state: "SP",
    country: "Brasil",
    category: "Umbanda Omolokô",
    tags: ["proteção", "caminhos", "trabalho"],
    rating: 4.9,
    followers: 9200,
    verified: true,
    boost: { level: "cidade", expiresAt: iso(-60 * 60 * 24 * 3) },
    highlight: { scope: "cidade", expiresAt: iso(-60 * 60 * 24 * 1) },
    createdAt: iso(60 * 60 * 24 * 700),
  },
];

export const seedClients: PersonalUser[] = [
  {
    id: "user_1",
    type: "personal",
    name: "Mariana Alves",
    email: "mari@cliente.app",
    password: "123456",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop&auto=format",
    bio: "Buscando meu caminho espiritual.",
    city: "São Paulo",
    state: "SP",
    country: "Brasil",
    interests: ["Oxum", "prosperidade", "amor"],
    createdAt: iso(60 * 60 * 24 * 30),
  },
  {
    id: "user_2",
    type: "personal",
    name: "Carlos Souza",
    email: "carlos@cliente.app",
    password: "123456",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&auto=format",
    city: "Belo Horizonte",
    state: "MG",
    country: "Brasil",
    interests: ["Ogum", "proteção"],
    createdAt: iso(60 * 60 * 24 * 90),
  },
];

export const seedUsers: User[] = [...seedHouses, ...seedClients];

export const seedRituals: Ritual[] = [
  {
    id: "rit_1",
    houseId: "casa_1",
    title: "Ritual da Prosperidade — Oxum Dourada",
    description:
      "Ritual completo para abertura de caminhos financeiros, com banho de descarrego, oferenda a Oxum e consulta individual por vídeo. Presencial em Salvador ou à distância.",
    cover: "https://images.unsplash.com/photo-1519452575417-564c1401ecc0?w=1200&h=800&fit=crop",
    price: 120,
    vagasTotal: 350,
    vagasVendidas: 214,
    mode: "hibrido",
    date: iso(-60 * 60 * 24 * 20),
    platformFeePct: 12,
    category: "prosperidade",
  },
  {
    id: "rit_2",
    houseId: "casa_2",
    title: "Trabalho de Justiça de Xangô",
    description: "Sessão coletiva para questões judiciais, contratos e reparação. Envie seu pedido por chat.",
    cover: "https://images.unsplash.com/photo-1541518763669-27fef9b49584?w=1200&h=800&fit=crop",
    price: 189,
    vagasTotal: 120,
    vagasVendidas: 78,
    mode: "distancia",
    date: iso(-60 * 60 * 24 * 10),
    platformFeePct: 10,
    category: "justiça",
  },
  {
    id: "rit_3",
    houseId: "casa_3",
    title: "Banho Sagrado das Sete Ondas",
    description: "Sequência de sete banhos com ervas e preces de Iemanjá para renovação espiritual.",
    cover: "https://images.unsplash.com/photo-1439405326854-014607f694d7?w=1200&h=800&fit=crop",
    price: 75,
    vagasTotal: 500,
    vagasVendidas: 342,
    mode: "distancia",
    date: iso(-60 * 60 * 24 * 5),
    platformFeePct: 15,
    category: "cura",
  },
  {
    id: "rit_4",
    houseId: "casa_4",
    title: "Ritual de Ogum — Corte de Demandas",
    description: "Ritual de força e proteção, corta demandas, olho gordo e amarras espirituais.",
    cover: "https://images.unsplash.com/photo-1518709414768-a88981a4515d?w=1200&h=800&fit=crop",
    price: 149,
    vagasTotal: 200,
    vagasVendidas: 187,
    mode: "presencial",
    date: iso(-60 * 60 * 24 * 15),
    platformFeePct: 12,
    category: "proteção",
  },
  {
    id: "rit_5",
    houseId: "casa_1",
    title: "Jogo de Búzios Personalizado",
    description: "Consulta individual pelas mãos da Ialorixá Dandara. Feito online ou presencial.",
    cover: "https://images.unsplash.com/photo-1509228468518-180dd4864904?w=1200&h=800&fit=crop",
    price: 90,
    vagasTotal: 80,
    vagasVendidas: 41,
    mode: "hibrido",
    date: iso(-60 * 60 * 24 * 8),
    platformFeePct: 10,
    category: "consulta",
  },
];

export const seedPosts: Post[] = [
  {
    id: "post_1",
    houseId: "casa_1",
    content: "Axé, meus filhos! Abrimos as vagas para o Ritual da Prosperidade de Oxum. Corre que estão acabando 🌊✨",
    image: "https://images.unsplash.com/photo-1519452575417-564c1401ecc0?w=1200&h=800&fit=crop",
    kind: "ritual",
    ritualId: "rit_1",
    likes: ["user_1", "user_2"],
    comments: [
      { id: "c1", userId: "user_1", text: "Já garanti a minha vaga! 🙏", createdAt: iso(60 * 30) },
    ],
    createdAt: iso(60 * 60 * 2),
  },
  {
    id: "post_2",
    houseId: "casa_2",
    content: "Xangô é justiça! Amanhã tem trabalho poderoso para quem está com pendências na justiça. Kaô Kabecilê!",
    image: "https://images.unsplash.com/photo-1541518763669-27fef9b49584?w=1200&h=800&fit=crop",
    kind: "trabalho",
    likes: ["user_2"],
    comments: [],
    createdAt: iso(60 * 60 * 5),
  },
  {
    id: "post_3",
    houseId: "casa_3",
    content: "Odoyá! Preparei a lista de ervas do banho das Sete Ondas. Contate o chat para receber as instruções.",
    kind: "geral",
    likes: [],
    comments: [],
    createdAt: iso(60 * 60 * 12),
  },
  {
    id: "post_4",
    houseId: "casa_4",
    content: "Ogum patacori! Vagas abertas para o ritual de corte de demandas — presencial em São Paulo.",
    image: "https://images.unsplash.com/photo-1518709414768-a88981a4515d?w=1200&h=800&fit=crop",
    kind: "ritual",
    ritualId: "rit_4",
    likes: ["user_1"],
    comments: [],
    createdAt: iso(60 * 60 * 20),
  },
  {
    id: "post_5",
    houseId: "casa_1",
    content: "Mãe Dandara acaba de abrir a agenda de Jogo de Búzios da semana. Reserve seu horário 🐚",
    kind: "buzios",
    ritualId: "rit_5",
    likes: [],
    comments: [],
    createdAt: iso(60 * 60 * 30),
  },
];

export const seedStories: Story[] = [
  { id: "s1", houseId: "casa_1", image: "https://images.unsplash.com/photo-1523712999610-f77fbcfc3843?w=600&h=1000&fit=crop", caption: "Preparando o axé", createdAt: iso(60 * 60 * 2) },
  { id: "s2", houseId: "casa_2", image: "https://images.unsplash.com/photo-1502134249126-9f3755a50d78?w=600&h=1000&fit=crop", caption: "Kaô!", createdAt: iso(60 * 60 * 3) },
  { id: "s3", houseId: "casa_3", image: "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?w=600&h=1000&fit=crop", caption: "Odoyá", createdAt: iso(60 * 60 * 4) },
  { id: "s4", houseId: "casa_4", image: "https://images.unsplash.com/photo-1470252649378-9c29740c9fa8?w=600&h=1000&fit=crop", caption: "Ogum ê", createdAt: iso(60 * 60 * 5) },
];

export const seedConversations: Conversation[] = [
  {
    id: "conv_1",
    participantIds: ["user_1", "casa_1"],
    messages: [
      { id: "m1", from: "user_1", to: "casa_1", text: "Mãe, gostaria de saber sobre o Ritual da Prosperidade.", createdAt: iso(60 * 60 * 3) },
      { id: "m2", from: "casa_1", to: "user_1", text: "Axé, minha filha! Ainda temos vagas. Deseja presencial ou à distância?", createdAt: iso(60 * 60 * 2) },
      { id: "m3", from: "user_1", to: "casa_1", text: "À distância mesmo, moro em SP.", createdAt: iso(60 * 60 * 1) },
    ],
    updatedAt: iso(60 * 60 * 1),
  },
];

export const boostCatalog: (BoostPlan & { label: string })[] = [
  { level: "cidade", days: 3, price: 39.9, label: "Cidade · 3 dias" },
  { level: "cidade", days: 7, price: 59.9, label: "Cidade · 7 dias" },
  { level: "cidade", days: 30, price: 99.9, label: "Cidade · 30 dias" },
  { level: "estado", days: 3, price: 89.9, label: "Estado · 3 dias" },
  { level: "estado", days: 7, price: 149.9, label: "Estado · 7 dias" },
  { level: "estado", days: 30, price: 249.9, label: "Estado · 30 dias" },
  { level: "pais", days: 3, price: 189.9, label: "Brasil · 3 dias" },
  { level: "pais", days: 7, price: 299.9, label: "Brasil · 7 dias" },
  { level: "pais", days: 30, price: 599.9, label: "Brasil · 30 dias" },
];

export const highlightCatalog = [
  { scope: "local", label: "Destaque Local", price: 29.9, description: "Sua casa em destaque no bairro por 7 dias." },
  { scope: "cidade", label: "Destaque Cidade", price: 79.9, description: "Marca em evidência em toda a cidade por 15 dias." },
  { scope: "pais", label: "Destaque Nacional", price: 349.9, description: "Sua casa aparece na home nacional por 15 dias." },
] as const;
